[package]
name = "turbocrab"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]

[dependencies]
hyper = "0.11"
hyper-tls = "0.1"
futures = "0.1"
url = "1.0"
tokio-core = "0.1"
failure = "0.1"
evmap = "3.0"
crossbeam-channel = "0.1"
